# Setup Cmake
CMAKE_MINIMUM_REQUIRED(VERSION 4.1)
SET(CMAKE_CXX_STANDARD 20)
CMAKE_POLICY(SET CMP0177 NEW)
SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Setup project
PROJECT(mcc C CXX)
FILE(GLOB_RECURSE COMPILER_SRCS src/*.cpp src/*.s)

# Create compiler
ADD_EXECUTABLE(mcc ${COMPILER_SRCS})
TARGET_INCLUDE_DIRECTORIES(mcc PRIVATE include)
